apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kruntimes.controller.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.controller.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kruntimes.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kruntimes.controller.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kruntimes.controller.name" . }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: controller
          image: {{ .Values.controller.image }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          args:
            - --leader-elect=true
            - --metrics-bind-address=:8082
            - --health-probe-bind-address=:8083
            - --default-daemon-image={{ .Values.runtimed.image }}
            - --runtimed-service-account-name={{ include "kruntimes.runtimed.name" . }}
          ports:
            - containerPort: 8082
              name: metrics
              protocol: TCP
            - containerPort: 8083
              name: probes
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
