apiVersion: apps/v1
kind: Deployment
metadata:
  name: kruntimes-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: kruntimes-controller
    {{- include "kruntimes.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kruntimes-controller
  template:
    metadata:
      labels:
        app: kruntimes-controller
    spec:
      serviceAccountName: kruntimes-controller
      containers:
        - name: controller
          image: {{ .Values.controller.image }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
          args:
            - --leader-elect=true
            - --metrics-bind-address=:8082
            - --health-probe-bind-address=:8083
          ports:
            - containerPort: 8082
              name: metrics
              protocol: TCP
            - containerPort: 8083
              name: probes
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
