{{- if and .Values.logAPI.enabled (not .Values.logAPI.tls.secretName) }}
{{- include "kruntimes.logAPI.ensureTLSCertificates" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kruntimes.logAPI.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.logAPI.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{ .Values.logAPI.tls.caBundleKey }}: {{ index .Values "_logAPICertificates" "caCert" | b64enc }}
  {{ .Values.logAPI.tls.certificateKey }}: {{ index .Values "_logAPICertificates" "tlsCert" | b64enc }}
  {{ .Values.logAPI.tls.privateKeyKey }}: {{ index .Values "_logAPICertificates" "tlsKey" | b64enc }}
{{- end }}
