apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kruntimes.scheduler.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.scheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      {{- include "kruntimes.scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kruntimes.scheduler.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kruntimes.scheduler.name" . }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: scheduler
          image: {{ .Values.scheduler.image }}
          imagePullPolicy: {{ .Values.scheduler.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          args:
            - --leader-elect={{ .Values.scheduler.leaderElect }}
            - --metrics-bind-address={{ .Values.scheduler.metricsBindAddress }}
            - --health-probe-bind-address={{ .Values.scheduler.probeBindAddress }}
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: probes
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
