apiVersion: v1
kind: ServiceAccount
metadata:
  name: kruntimes-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    app: kruntimes-scheduler
    {{- include "kruntimes.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kruntimes-runtimed
  namespace: {{ .Release.Namespace }}
  labels:
    app: kruntimes-runtimed
    {{- include "kruntimes.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kruntimes-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: kruntimes-controller
    {{- include "kruntimes.labels" . | nindent 4 }}
