apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kruntimes.scheduler.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.scheduler.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kruntimes.runtimed.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.runtimed.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kruntimes.controller.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.controller.labels" . | nindent 4 }}
