apiVersion: v1
kind: Service
metadata:
  name: {{ include "kruntimes.scheduler.name" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.scheduler.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    {{- include "kruntimes.scheduler.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kruntimes.controller.name" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.controller.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    {{- include "kruntimes.controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
