# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'runtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rruntime.proto\x12\x0b\x65xecutor.v1\"\xdc\x01\n\x0e\x45xecuteRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\x31\n\x03\x65nv\x18\x03 \x03(\x0b\x32$.executor.v1.ExecuteRequest.EnvEntry\x12\x17\n\x0ftimeout_seconds\x18\x04 \x01(\x03\x12\x13\n\x0bworking_dir\x18\x05 \x01(\t\x12\x12\n\nentrypoint\x18\x06 \x01(\t\x12\x0f\n\x07handler\x18\x07 \x01(\t\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1d\n\x0f\x45xecuteResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x1b\n\rStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x92\x01\n\x0eStatusResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12*\n\x05state\x18\x02 \x01(\x0e\x32\x1b.executor.v1.ExecutionState\x12\x11\n\texit_code\x18\x03 \x01(\x05\x12\x0e\n\x06stdout\x18\x04 \x01(\t\x12\x0e\n\x06stderr\x18\x05 \x01(\t\x12\x15\n\rerror_message\x18\x06 \x01(\t\"\r\n\x0bListRequest\"<\n\x0cListResponse\x12,\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1b.executor.v1.StatusResponse\"\x1b\n\rCancelRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x10\n\x0e\x43\x61ncelResponse*\xa6\x01\n\x0e\x45xecutionState\x12\x1f\n\x1b\x45XECUTION_STATE_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x45XECUTION_STATE_PENDING\x10\x01\x12\x1b\n\x17\x45XECUTION_STATE_RUNNING\x10\x02\x12\x1d\n\x19\x45XECUTION_STATE_SUCCEEDED\x10\x03\x12\x1a\n\x16\x45XECUTION_STATE_FAILED\x10\x04\x32\x92\x02\n\x07Runtime\x12\x44\n\x07\x45xecute\x12\x1b.executor.v1.ExecuteRequest\x1a\x1c.executor.v1.ExecuteResponse\x12\x41\n\x06Status\x12\x1a.executor.v1.StatusRequest\x1a\x1b.executor.v1.StatusResponse\x12;\n\x04List\x12\x18.executor.v1.ListRequest\x1a\x19.executor.v1.ListResponse\x12\x41\n\x06\x43\x61ncel\x12\x1a.executor.v1.CancelRequest\x1a\x1b.executor.v1.CancelResponseB9Z7github.com/kruntimes/kruntimes/api/runtime/v1;runtimev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/kruntimes/kruntimes/api/runtime/v1;runtimev1'
  _globals['_EXECUTEREQUEST_ENVENTRY']._loaded_options = None
  _globals['_EXECUTEREQUEST_ENVENTRY']._serialized_options = b'8\001'
  _globals['_EXECUTIONSTATE']._serialized_start=587
  _globals['_EXECUTIONSTATE']._serialized_end=753
  _globals['_EXECUTEREQUEST']._serialized_start=31
  _globals['_EXECUTEREQUEST']._serialized_end=251
  _globals['_EXECUTEREQUEST_ENVENTRY']._serialized_start=209
  _globals['_EXECUTEREQUEST_ENVENTRY']._serialized_end=251
  _globals['_EXECUTERESPONSE']._serialized_start=253
  _globals['_EXECUTERESPONSE']._serialized_end=282
  _globals['_STATUSREQUEST']._serialized_start=284
  _globals['_STATUSREQUEST']._serialized_end=311
  _globals['_STATUSRESPONSE']._serialized_start=314
  _globals['_STATUSRESPONSE']._serialized_end=460
  _globals['_LISTREQUEST']._serialized_start=462
  _globals['_LISTREQUEST']._serialized_end=475
  _globals['_LISTRESPONSE']._serialized_start=477
  _globals['_LISTRESPONSE']._serialized_end=537
  _globals['_CANCELREQUEST']._serialized_start=539
  _globals['_CANCELREQUEST']._serialized_end=566
  _globals['_CANCELRESPONSE']._serialized_start=568
  _globals['_CANCELRESPONSE']._serialized_end=584
  _globals['_RUNTIME']._serialized_start=756
  _globals['_RUNTIME']._serialized_end=1030
# @@protoc_insertion_point(module_scope)
