apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kruntime-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kruntime-agent
subjects:
  - kind: ServiceAccount
    name: kruntime-agent
    namespace: default
