apiVersion: kruntimes.io/v1alpha1
kind: Runtime
metadata:
  name: bash
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes-runtimes.labels" . | nindent 4 }}
spec:
  image: {{ include "kruntimes-runtimes.image" (list . .Values.bash.image) }}
  port: {{ .Values.bash.port }}
  replicas: {{ .Values.bash.replicas }}
  capacity:
    {{- toYaml .Values.bash.capacity | nindent 4 }}
  resources:
    {{- toYaml .Values.bash.resources | nindent 4 }}
  workspace:
    sizeLimit: {{ .Values.workspace.sizeLimit | quote }}
  command:
    - --port={{ .Values.bash.port }}
    - --work-dir=/workspace
