apiVersion: kruntimes.io/v1alpha1
kind: Runtime
metadata:
  name: python
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes-runtimes.labels" . | nindent 4 }}
spec:
  port: {{ .Values.python.port }}
  replicas: {{ .Values.python.replicas }}
  capacity:
    {{- toYaml .Values.python.capacity | nindent 4 }}
  workspace:
    sizeLimit: {{ .Values.workspace.sizeLimit | quote }}
  template:
    spec:
      containers:
        - name: runtime
          image: {{ include "kruntimes-runtimes.image" (list . .Values.python.image) }}
          args:
            - --port={{ .Values.python.port }}
            - --work-dir=/workspace
          resources:
            {{- toYaml .Values.python.resources | nindent 12 }}
