// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/taskruntime/v1/taskruntime.proto

package taskruntimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 1
	TaskState_TASK_STATE_RUNNING     TaskState = 2
	TaskState_TASK_STATE_SUCCEEDED   TaskState = 3
	TaskState_TASK_STATE_FAILED      TaskState = 4
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_PENDING",
		2: "TASK_STATE_RUNNING",
		3: "TASK_STATE_SUCCEEDED",
		4: "TASK_STATE_FAILED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_RUNNING":     2,
		"TASK_STATE_SUCCEEDED":   3,
		"TASK_STATE_FAILED":      4,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_taskruntime_v1_taskruntime_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_api_taskruntime_v1_taskruntime_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_api_taskruntime_v1_taskruntime_proto_rawDescGZIP(), []int{0}
}

type CreateTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Commands       []string               `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	Env            map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int64                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_taskruntime_v1_taskruntime_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTaskRequest) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *CreateTaskRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CreateTaskRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CreateTaskRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_taskruntime_v1_taskruntime_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_taskruntime_v1_taskruntime_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         TaskState              `protobuf:"varint,2,opt,name=state,proto3,enum=taskruntime.v1.TaskState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_taskruntime_v1_taskruntime_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTaskResponse) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *GetTaskResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *GetTaskResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *GetTaskResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *GetTaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_taskruntime_v1_taskruntime_proto_rawDescGZIP(), []int{4}
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*GetTaskResponse     `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_taskruntime_v1_taskruntime_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksResponse) GetTasks() []*GetTaskResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_taskruntime_v1_taskruntime_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_taskruntime_v1_taskruntime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_taskruntime_v1_taskruntime_proto_rawDescGZIP(), []int{7}
}

var File_api_taskruntime_v1_taskruntime_proto protoreflect.FileDescriptor

const file_api_taskruntime_v1_taskruntime_proto_rawDesc = "" +
	"\n" +
	"$api/taskruntime/v1/taskruntime.proto\x12\x0etaskruntime.v1\"\xff\x01\n" +
	"\x11CreateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcommands\x18\x02 \x03(\tR\bcommands\x12<\n" +
	"\x03env\x18\x03 \x03(\v2*.taskruntime.v1.CreateTaskRequest.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x03R\x0etimeoutSeconds\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x12CreateTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc4\x01\n" +
	"\x0fGetTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x05state\x18\x02 \x01(\x0e2\x19.taskruntime.v1.TaskStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\x12\n" +
	"\x10ListTasksRequest\"J\n" +
	"\x11ListTasksResponse\x125\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1f.taskruntime.v1.GetTaskResponseR\x05tasks\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteTaskResponse*\x88\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x042\xd5\x02\n" +
	"\vTaskRuntime\x12S\n" +
	"\n" +
	"CreateTask\x12!.taskruntime.v1.CreateTaskRequest\x1a\".taskruntime.v1.CreateTaskResponse\x12J\n" +
	"\aGetTask\x12\x1e.taskruntime.v1.GetTaskRequest\x1a\x1f.taskruntime.v1.GetTaskResponse\x12P\n" +
	"\tListTasks\x12 .taskruntime.v1.ListTasksRequest\x1a!.taskruntime.v1.ListTasksResponse\x12S\n" +
	"\n" +
	"DeleteTask\x12!.taskruntime.v1.DeleteTaskRequest\x1a\".taskruntime.v1.DeleteTaskResponseBAZ?github.com/airconduct/kruntime/api/taskruntime/v1;taskruntimev1b\x06proto3"

var (
	file_api_taskruntime_v1_taskruntime_proto_rawDescOnce sync.Once
	file_api_taskruntime_v1_taskruntime_proto_rawDescData []byte
)

func file_api_taskruntime_v1_taskruntime_proto_rawDescGZIP() []byte {
	file_api_taskruntime_v1_taskruntime_proto_rawDescOnce.Do(func() {
		file_api_taskruntime_v1_taskruntime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_taskruntime_v1_taskruntime_proto_rawDesc), len(file_api_taskruntime_v1_taskruntime_proto_rawDesc)))
	})
	return file_api_taskruntime_v1_taskruntime_proto_rawDescData
}

var file_api_taskruntime_v1_taskruntime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_taskruntime_v1_taskruntime_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_taskruntime_v1_taskruntime_proto_goTypes = []any{
	(TaskState)(0),             // 0: taskruntime.v1.TaskState
	(*CreateTaskRequest)(nil),  // 1: taskruntime.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil), // 2: taskruntime.v1.CreateTaskResponse
	(*GetTaskRequest)(nil),     // 3: taskruntime.v1.GetTaskRequest
	(*GetTaskResponse)(nil),    // 4: taskruntime.v1.GetTaskResponse
	(*ListTasksRequest)(nil),   // 5: taskruntime.v1.ListTasksRequest
	(*ListTasksResponse)(nil),  // 6: taskruntime.v1.ListTasksResponse
	(*DeleteTaskRequest)(nil),  // 7: taskruntime.v1.DeleteTaskRequest
	(*DeleteTaskResponse)(nil), // 8: taskruntime.v1.DeleteTaskResponse
	nil,                        // 9: taskruntime.v1.CreateTaskRequest.EnvEntry
}
var file_api_taskruntime_v1_taskruntime_proto_depIdxs = []int32{
	9, // 0: taskruntime.v1.CreateTaskRequest.env:type_name -> taskruntime.v1.CreateTaskRequest.EnvEntry
	0, // 1: taskruntime.v1.GetTaskResponse.state:type_name -> taskruntime.v1.TaskState
	4, // 2: taskruntime.v1.ListTasksResponse.tasks:type_name -> taskruntime.v1.GetTaskResponse
	1, // 3: taskruntime.v1.TaskRuntime.CreateTask:input_type -> taskruntime.v1.CreateTaskRequest
	3, // 4: taskruntime.v1.TaskRuntime.GetTask:input_type -> taskruntime.v1.GetTaskRequest
	5, // 5: taskruntime.v1.TaskRuntime.ListTasks:input_type -> taskruntime.v1.ListTasksRequest
	7, // 6: taskruntime.v1.TaskRuntime.DeleteTask:input_type -> taskruntime.v1.DeleteTaskRequest
	2, // 7: taskruntime.v1.TaskRuntime.CreateTask:output_type -> taskruntime.v1.CreateTaskResponse
	4, // 8: taskruntime.v1.TaskRuntime.GetTask:output_type -> taskruntime.v1.GetTaskResponse
	6, // 9: taskruntime.v1.TaskRuntime.ListTasks:output_type -> taskruntime.v1.ListTasksResponse
	8, // 10: taskruntime.v1.TaskRuntime.DeleteTask:output_type -> taskruntime.v1.DeleteTaskResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_taskruntime_v1_taskruntime_proto_init() }
func file_api_taskruntime_v1_taskruntime_proto_init() {
	if File_api_taskruntime_v1_taskruntime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_taskruntime_v1_taskruntime_proto_rawDesc), len(file_api_taskruntime_v1_taskruntime_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_taskruntime_v1_taskruntime_proto_goTypes,
		DependencyIndexes: file_api_taskruntime_v1_taskruntime_proto_depIdxs,
		EnumInfos:         file_api_taskruntime_v1_taskruntime_proto_enumTypes,
		MessageInfos:      file_api_taskruntime_v1_taskruntime_proto_msgTypes,
	}.Build()
	File_api_taskruntime_v1_taskruntime_proto = out.File
	file_api_taskruntime_v1_taskruntime_proto_goTypes = nil
	file_api_taskruntime_v1_taskruntime_proto_depIdxs = nil
}
