// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/artifact/v1/artifact.proto

package artifactv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RunName       string                 `protobuf:"bytes,2,opt,name=run_name,json=runName,proto3" json:"run_name,omitempty"`
	ArtifactName  string                 `protobuf:"bytes,3,opt,name=artifact_name,json=artifactName,proto3" json:"artifact_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_api_artifact_v1_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_artifact_v1_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_api_artifact_v1_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DownloadRequest) GetRunName() string {
	if x != nil {
		return x.RunName
	}
	return ""
}

func (x *DownloadRequest) GetArtifactName() string {
	if x != nil {
		return x.ArtifactName
	}
	return ""
}

type ArtifactMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Digest        string                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactMetadata) Reset() {
	*x = ArtifactMetadata{}
	mi := &file_api_artifact_v1_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactMetadata) ProtoMessage() {}

func (x *ArtifactMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_artifact_v1_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactMetadata.ProtoReflect.Descriptor instead.
func (*ArtifactMetadata) Descriptor() ([]byte, []int) {
	return file_api_artifact_v1_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ArtifactMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ArtifactMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactMetadata) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type DownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// metadata is set on the first response only.
	Metadata *ArtifactMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// data contains at most 64 KiB and is set on responses after metadata.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_api_artifact_v1_artifact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_artifact_v1_artifact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_api_artifact_v1_artifact_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadResponse) GetMetadata() *ArtifactMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DownloadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_artifact_v1_artifact_proto protoreflect.FileDescriptor

const file_api_artifact_v1_artifact_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/artifact/v1/artifact.proto\x12\vartifact.v1\"o\n" +
	"\x0fDownloadRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\brun_name\x18\x02 \x01(\tR\arunName\x12#\n" +
	"\rartifact_name\x18\x03 \x01(\tR\fartifactName\"\x94\x01\n" +
	"\x10ArtifactMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\"a\n" +
	"\x10DownloadResponse\x129\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1d.artifact.v1.ArtifactMetadataR\bmetadata\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2\\\n" +
	"\x0fArtifactService\x12I\n" +
	"\bDownload\x12\x1c.artifact.v1.DownloadRequest\x1a\x1d.artifact.v1.DownloadResponse0\x01B;Z9github.com/kruntimes/kruntimes/api/artifact/v1;artifactv1b\x06proto3"

var (
	file_api_artifact_v1_artifact_proto_rawDescOnce sync.Once
	file_api_artifact_v1_artifact_proto_rawDescData []byte
)

func file_api_artifact_v1_artifact_proto_rawDescGZIP() []byte {
	file_api_artifact_v1_artifact_proto_rawDescOnce.Do(func() {
		file_api_artifact_v1_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_artifact_v1_artifact_proto_rawDesc), len(file_api_artifact_v1_artifact_proto_rawDesc)))
	})
	return file_api_artifact_v1_artifact_proto_rawDescData
}

var file_api_artifact_v1_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_artifact_v1_artifact_proto_goTypes = []any{
	(*DownloadRequest)(nil),  // 0: artifact.v1.DownloadRequest
	(*ArtifactMetadata)(nil), // 1: artifact.v1.ArtifactMetadata
	(*DownloadResponse)(nil), // 2: artifact.v1.DownloadResponse
}
var file_api_artifact_v1_artifact_proto_depIdxs = []int32{
	1, // 0: artifact.v1.DownloadResponse.metadata:type_name -> artifact.v1.ArtifactMetadata
	0, // 1: artifact.v1.ArtifactService.Download:input_type -> artifact.v1.DownloadRequest
	2, // 2: artifact.v1.ArtifactService.Download:output_type -> artifact.v1.DownloadResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_artifact_v1_artifact_proto_init() }
func file_api_artifact_v1_artifact_proto_init() {
	if File_api_artifact_v1_artifact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_artifact_v1_artifact_proto_rawDesc), len(file_api_artifact_v1_artifact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_artifact_v1_artifact_proto_goTypes,
		DependencyIndexes: file_api_artifact_v1_artifact_proto_depIdxs,
		MessageInfos:      file_api_artifact_v1_artifact_proto_msgTypes,
	}.Build()
	File_api_artifact_v1_artifact_proto = out.File
	file_api_artifact_v1_artifact_proto_goTypes = nil
	file_api_artifact_v1_artifact_proto_depIdxs = nil
}
