apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kruntime-controller
  labels:
    {{- include "kruntime.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - kruntime.airconduct.com
    resources:
      - runtimes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kruntime.airconduct.com
    resources:
      - runtimes/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kruntime-controller
  labels:
    {{- include "kruntime.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kruntime-controller
subjects:
  - kind: ServiceAccount
    name: kruntime-controller
    namespace: {{ .Release.Namespace }}
