apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kruntime-runtimed
  labels:
    {{- include "kruntime.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - kruntime.aionops.com
    resources:
      - runs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kruntime.aionops.com
    resources:
      - runs/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kruntime-runtimed
  labels:
    {{- include "kruntime.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kruntime-runtimed
subjects:
  - kind: ServiceAccount
    name: kruntime-runtimed
    namespace: {{ .Release.Namespace }}
