apiVersion: v1
kind: ServiceAccount
metadata:
  name: kruntime-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    app: kruntime-scheduler
    {{- include "kruntime.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kruntime-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: kruntime-agent
    {{- include "kruntime.labels" . | nindent 4 }}
