// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/runtime/v1/runtime.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionState int32

const (
	ExecutionState_EXECUTION_STATE_UNSPECIFIED ExecutionState = 0
	ExecutionState_EXECUTION_STATE_PENDING     ExecutionState = 1
	ExecutionState_EXECUTION_STATE_RUNNING     ExecutionState = 2
	ExecutionState_EXECUTION_STATE_SUCCEEDED   ExecutionState = 3
	ExecutionState_EXECUTION_STATE_FAILED      ExecutionState = 4
)

// Enum value maps for ExecutionState.
var (
	ExecutionState_name = map[int32]string{
		0: "EXECUTION_STATE_UNSPECIFIED",
		1: "EXECUTION_STATE_PENDING",
		2: "EXECUTION_STATE_RUNNING",
		3: "EXECUTION_STATE_SUCCEEDED",
		4: "EXECUTION_STATE_FAILED",
	}
	ExecutionState_value = map[string]int32{
		"EXECUTION_STATE_UNSPECIFIED": 0,
		"EXECUTION_STATE_PENDING":     1,
		"EXECUTION_STATE_RUNNING":     2,
		"EXECUTION_STATE_SUCCEEDED":   3,
		"EXECUTION_STATE_FAILED":      4,
	}
)

func (x ExecutionState) Enum() *ExecutionState {
	p := new(ExecutionState)
	*p = x
	return p
}

func (x ExecutionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_runtime_v1_runtime_proto_enumTypes[0].Descriptor()
}

func (ExecutionState) Type() protoreflect.EnumType {
	return &file_api_runtime_v1_runtime_proto_enumTypes[0]
}

func (x ExecutionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionState.Descriptor instead.
func (ExecutionState) EnumDescriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Commands       []string               `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	Env            map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int64                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecuteRequest) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecuteRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         ExecutionState         `protobuf:"varint,2,opt,name=state,proto3,enum=executor.v1.ExecutionState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusResponse) GetState() ExecutionState {
	if x != nil {
		return x.State
	}
	return ExecutionState_EXECUTION_STATE_UNSPECIFIED
}

func (x *StatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StatusResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *StatusResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *StatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*StatusResponse      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetEntries() []*StatusResponse {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

var File_api_runtime_v1_runtime_proto protoreflect.FileDescriptor

const file_api_runtime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1capi/runtime/v1/runtime.proto\x12\vexecutor.v1\"\xf6\x01\n" +
	"\x0eExecuteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcommands\x18\x02 \x03(\tR\bcommands\x126\n" +
	"\x03env\x18\x03 \x03(\v2$.executor.v1.ExecuteRequest.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x03R\x0etimeoutSeconds\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\x0fExecuteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc5\x01\n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1b.executor.v1.ExecutionStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\r\n" +
	"\vListRequest\"E\n" +
	"\fListResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.executor.v1.StatusResponseR\aentries\"\x1f\n" +
	"\rCancelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eCancelResponse*\xa6\x01\n" +
	"\x0eExecutionState\x12\x1f\n" +
	"\x1bEXECUTION_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EXECUTION_STATE_PENDING\x10\x01\x12\x1b\n" +
	"\x17EXECUTION_STATE_RUNNING\x10\x02\x12\x1d\n" +
	"\x19EXECUTION_STATE_SUCCEEDED\x10\x03\x12\x1a\n" +
	"\x16EXECUTION_STATE_FAILED\x10\x042\x92\x02\n" +
	"\aRuntime\x12D\n" +
	"\aExecute\x12\x1b.executor.v1.ExecuteRequest\x1a\x1c.executor.v1.ExecuteResponse\x12A\n" +
	"\x06Status\x12\x1a.executor.v1.StatusRequest\x1a\x1b.executor.v1.StatusResponse\x12;\n" +
	"\x04List\x12\x18.executor.v1.ListRequest\x1a\x19.executor.v1.ListResponse\x12A\n" +
	"\x06Cancel\x12\x1a.executor.v1.CancelRequest\x1a\x1b.executor.v1.CancelResponseB9Z7github.com/airconduct/kruntime/api/runtime/v1;runtimev1b\x06proto3"

var (
	file_api_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_api_runtime_v1_runtime_proto_rawDescData []byte
)

func file_api_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_api_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_api_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_runtime_v1_runtime_proto_rawDesc), len(file_api_runtime_v1_runtime_proto_rawDesc)))
	})
	return file_api_runtime_v1_runtime_proto_rawDescData
}

var file_api_runtime_v1_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_runtime_v1_runtime_proto_goTypes = []any{
	(ExecutionState)(0),     // 0: executor.v1.ExecutionState
	(*ExecuteRequest)(nil),  // 1: executor.v1.ExecuteRequest
	(*ExecuteResponse)(nil), // 2: executor.v1.ExecuteResponse
	(*StatusRequest)(nil),   // 3: executor.v1.StatusRequest
	(*StatusResponse)(nil),  // 4: executor.v1.StatusResponse
	(*ListRequest)(nil),     // 5: executor.v1.ListRequest
	(*ListResponse)(nil),    // 6: executor.v1.ListResponse
	(*CancelRequest)(nil),   // 7: executor.v1.CancelRequest
	(*CancelResponse)(nil),  // 8: executor.v1.CancelResponse
	nil,                     // 9: executor.v1.ExecuteRequest.EnvEntry
}
var file_api_runtime_v1_runtime_proto_depIdxs = []int32{
	9, // 0: executor.v1.ExecuteRequest.env:type_name -> executor.v1.ExecuteRequest.EnvEntry
	0, // 1: executor.v1.StatusResponse.state:type_name -> executor.v1.ExecutionState
	4, // 2: executor.v1.ListResponse.entries:type_name -> executor.v1.StatusResponse
	1, // 3: executor.v1.Runtime.Execute:input_type -> executor.v1.ExecuteRequest
	3, // 4: executor.v1.Runtime.Status:input_type -> executor.v1.StatusRequest
	5, // 5: executor.v1.Runtime.List:input_type -> executor.v1.ListRequest
	7, // 6: executor.v1.Runtime.Cancel:input_type -> executor.v1.CancelRequest
	2, // 7: executor.v1.Runtime.Execute:output_type -> executor.v1.ExecuteResponse
	4, // 8: executor.v1.Runtime.Status:output_type -> executor.v1.StatusResponse
	6, // 9: executor.v1.Runtime.List:output_type -> executor.v1.ListResponse
	8, // 10: executor.v1.Runtime.Cancel:output_type -> executor.v1.CancelResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_runtime_v1_runtime_proto_init() }
func file_api_runtime_v1_runtime_proto_init() {
	if File_api_runtime_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_runtime_v1_runtime_proto_rawDesc), len(file_api_runtime_v1_runtime_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_api_runtime_v1_runtime_proto_depIdxs,
		EnumInfos:         file_api_runtime_v1_runtime_proto_enumTypes,
		MessageInfos:      file_api_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_api_runtime_v1_runtime_proto = out.File
	file_api_runtime_v1_runtime_proto_goTypes = nil
	file_api_runtime_v1_runtime_proto_depIdxs = nil
}
