{{- if .Values.console.tls.selfSigned }}
{{- include "kruntimes.console.validateTLS" . }}
{{- include "kruntimes.console.ensureTLSCertificates" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kruntimes.console.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.console.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{ .Values.console.tls.caBundleKey }}: {{ index .Values "_consoleCertificates" "caCert" | b64enc }}
  {{ .Values.console.tls.certificateKey }}: {{ index .Values "_consoleCertificates" "tlsCert" | b64enc }}
  {{ .Values.console.tls.privateKeyKey }}: {{ index .Values "_consoleCertificates" "tlsKey" | b64enc }}
{{- end }}
