apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kruntimes.console.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.console.labels" . | nindent 4 }}
